// @ts-nocheck
import React from 'react';
import { dynamic } from 'dumi';
import rawCode1 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/design.jsx?dumi-raw-code';
import rawCode2 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/App.jsx?dumi-raw-code';
import rawCode3 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/set/index.js?dumi-raw-code';
import rawCode4 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/UseDelegator.js?dumi-raw-code';
import rawCode5 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/msgCompConfig.js?dumi-raw-code';
import rawCode6 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/add/index.js?dumi-raw-code';
import rawCode7 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/api/asset.js?dumi-raw-code';
import rawCode8 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/api/request.js?dumi-raw-code';
import rawCode9 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/themeColor.js?dumi-raw-code';
import rawCode10 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/child/index.js?dumi-raw-code';
import rawCode11 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/table/index.js?dumi-raw-code';
import rawCode12 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/preview/index.js?dumi-raw-code';
import rawCode13 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/src/components/designConfiguration/index.js?dumi-raw-code';
import rawCode14 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/mockComponentCenter.ts?dumi-raw-code';
import rawCode15 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/designConfiguration.jsx?dumi-raw-code';
import rawCode16 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/formMain.jsx?dumi-raw-code';
import rawCode17 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/formChild.jsx?dumi-raw-code';
import rawCode18 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/table.jsx?dumi-raw-code';
import rawCode19 from '!!dumi-raw-code-loader!D:/workTest/历下城发/build/demo/detail.jsx?dumi-raw-code';

export default {
  'build-design': {
    component: (require('D:/workTest/历下城发/build/demo/design.jsx')).default,
    previewerProps: {"sources":{"_":{"jsx":rawCode1},"src/App.jsx":{"import":"../src/App","content":rawCode2},"src/components/set/index.js":{"import":"./components/set","content":rawCode3},"src/UseDelegator.js":{"import":"../../UseDelegator","content":rawCode4},"src/msgCompConfig.js":{"import":"../../msgCompConfig","content":rawCode5},"src/components/add/index.js":{"import":"./components/add","content":rawCode6},"src/api/asset.js":{"import":"../../api/asset","content":rawCode7},"src/api/request.js":{"import":"./request","content":rawCode8},"src/components/themeColor.js":{"import":"../themeColor","content":rawCode9},"src/components/child/index.js":{"import":"./components/child","content":rawCode10},"src/components/table/index.js":{"import":"./components/table","content":rawCode11},"src/components/preview/index.js":{"import":"./components/preview","content":rawCode12},"src/components/designConfiguration/index.js":{"import":"./components/designConfiguration","content":rawCode13},"mockComponentCenter.ts":{"import":"./mockComponentCenter","content":rawCode14}},"dependencies":{"react":{"version":">=16.9.0"},"antd":{"version":"4.24.3","css":"antd/dist/antd.css"},"react-dom":{"version":">=16.9.0"},"prop-types":{"version":"15.8.1"},"moment":{"version":"2.29.4"},"axios":{"version":"0.21.4"},"querystringify":{"version":"2.2.0"}},"identifier":"build-design"},
  },
  'build-designconfiguration': {
    component: (require('D:/workTest/历下城发/build/demo/designConfiguration.jsx')).default,
    previewerProps: {"sources":{"_":{"jsx":rawCode15},"src/App.jsx":{"import":"../src/App","content":rawCode2},"src/components/set/index.js":{"import":"./components/set","content":rawCode3},"src/UseDelegator.js":{"import":"../../UseDelegator","content":rawCode4},"src/msgCompConfig.js":{"import":"../../msgCompConfig","content":rawCode5},"src/components/add/index.js":{"import":"./components/add","content":rawCode6},"src/api/asset.js":{"import":"../../api/asset","content":rawCode7},"src/api/request.js":{"import":"./request","content":rawCode8},"src/components/themeColor.js":{"import":"../themeColor","content":rawCode9},"src/components/child/index.js":{"import":"./components/child","content":rawCode10},"src/components/table/index.js":{"import":"./components/table","content":rawCode11},"src/components/preview/index.js":{"import":"./components/preview","content":rawCode12},"src/components/designConfiguration/index.js":{"import":"./components/designConfiguration","content":rawCode13},"mockComponentCenter.ts":{"import":"./mockComponentCenter","content":rawCode14}},"dependencies":{"react":{"version":">=16.9.0"},"prop-types":{"version":"15.8.1"},"antd":{"version":"4.24.3","css":"antd/dist/antd.css"},"react-dom":{"version":">=16.9.0"},"moment":{"version":"2.29.4"},"axios":{"version":"0.21.4"},"querystringify":{"version":"2.2.0"}},"identifier":"build-designconfiguration"},
  },
  'build-formmain': {
    component: (require('D:/workTest/历下城发/build/demo/formMain.jsx')).default,
    previewerProps: {"sources":{"_":{"jsx":rawCode16},"src/App.jsx":{"import":"../src/App","content":rawCode2},"src/components/set/index.js":{"import":"./components/set","content":rawCode3},"src/UseDelegator.js":{"import":"../../UseDelegator","content":rawCode4},"src/msgCompConfig.js":{"import":"../../msgCompConfig","content":rawCode5},"src/components/add/index.js":{"import":"./components/add","content":rawCode6},"src/api/asset.js":{"import":"../../api/asset","content":rawCode7},"src/api/request.js":{"import":"./request","content":rawCode8},"src/components/themeColor.js":{"import":"../themeColor","content":rawCode9},"src/components/child/index.js":{"import":"./components/child","content":rawCode10},"src/components/table/index.js":{"import":"./components/table","content":rawCode11},"src/components/preview/index.js":{"import":"./components/preview","content":rawCode12},"src/components/designConfiguration/index.js":{"import":"./components/designConfiguration","content":rawCode13},"mockComponentCenter.ts":{"import":"./mockComponentCenter","content":rawCode14}},"dependencies":{"react":{"version":">=16.9.0"},"antd":{"version":"4.24.3","css":"antd/dist/antd.css"},"react-dom":{"version":">=16.9.0"},"prop-types":{"version":"15.8.1"},"moment":{"version":"2.29.4"},"axios":{"version":"0.21.4"},"querystringify":{"version":"2.2.0"}},"identifier":"build-formmain"},
  },
  'build-formchild': {
    component: (require('D:/workTest/历下城发/build/demo/formChild.jsx')).default,
    previewerProps: {"sources":{"_":{"jsx":rawCode17},"src/App.jsx":{"import":"../src/App","content":rawCode2},"src/components/set/index.js":{"import":"./components/set","content":rawCode3},"src/UseDelegator.js":{"import":"../../UseDelegator","content":rawCode4},"src/msgCompConfig.js":{"import":"../../msgCompConfig","content":rawCode5},"src/components/add/index.js":{"import":"./components/add","content":rawCode6},"src/api/asset.js":{"import":"../../api/asset","content":rawCode7},"src/api/request.js":{"import":"./request","content":rawCode8},"src/components/themeColor.js":{"import":"../themeColor","content":rawCode9},"src/components/child/index.js":{"import":"./components/child","content":rawCode10},"src/components/table/index.js":{"import":"./components/table","content":rawCode11},"src/components/preview/index.js":{"import":"./components/preview","content":rawCode12},"src/components/designConfiguration/index.js":{"import":"./components/designConfiguration","content":rawCode13},"mockComponentCenter.ts":{"import":"./mockComponentCenter","content":rawCode14}},"dependencies":{"react":{"version":">=16.9.0"},"prop-types":{"version":"15.8.1"},"antd":{"version":"4.24.3","css":"antd/dist/antd.css"},"react-dom":{"version":">=16.9.0"},"moment":{"version":"2.29.4"},"axios":{"version":"0.21.4"},"querystringify":{"version":"2.2.0"}},"identifier":"build-formchild"},
  },
  'build-table': {
    component: (require('D:/workTest/历下城发/build/demo/table.jsx')).default,
    previewerProps: {"sources":{"_":{"jsx":rawCode18},"src/App.jsx":{"import":"../src/App","content":rawCode2},"src/components/set/index.js":{"import":"./components/set","content":rawCode3},"src/UseDelegator.js":{"import":"../../UseDelegator","content":rawCode4},"src/msgCompConfig.js":{"import":"../../msgCompConfig","content":rawCode5},"src/components/add/index.js":{"import":"./components/add","content":rawCode6},"src/api/asset.js":{"import":"../../api/asset","content":rawCode7},"src/api/request.js":{"import":"./request","content":rawCode8},"src/components/themeColor.js":{"import":"../themeColor","content":rawCode9},"src/components/child/index.js":{"import":"./components/child","content":rawCode10},"src/components/table/index.js":{"import":"./components/table","content":rawCode11},"src/components/preview/index.js":{"import":"./components/preview","content":rawCode12},"src/components/designConfiguration/index.js":{"import":"./components/designConfiguration","content":rawCode13}},"dependencies":{"react":{"version":">=16.9.0"},"prop-types":{"version":"15.8.1"},"antd":{"version":"4.24.3","css":"antd/dist/antd.css"},"react-dom":{"version":">=16.9.0"},"moment":{"version":"2.29.4"},"axios":{"version":"0.21.4"},"querystringify":{"version":"2.2.0"}},"identifier":"build-table"},
  },
  'build-detail': {
    component: (require('D:/workTest/历下城发/build/demo/detail.jsx')).default,
    previewerProps: {"sources":{"_":{"jsx":rawCode19},"src/App.jsx":{"import":"../src/App","content":rawCode2},"src/components/set/index.js":{"import":"./components/set","content":rawCode3},"src/UseDelegator.js":{"import":"../../UseDelegator","content":rawCode4},"src/msgCompConfig.js":{"import":"../../msgCompConfig","content":rawCode5},"src/components/add/index.js":{"import":"./components/add","content":rawCode6},"src/api/asset.js":{"import":"../../api/asset","content":rawCode7},"src/api/request.js":{"import":"./request","content":rawCode8},"src/components/themeColor.js":{"import":"../themeColor","content":rawCode9},"src/components/child/index.js":{"import":"./components/child","content":rawCode10},"src/components/table/index.js":{"import":"./components/table","content":rawCode11},"src/components/preview/index.js":{"import":"./components/preview","content":rawCode12},"src/components/designConfiguration/index.js":{"import":"./components/designConfiguration","content":rawCode13}},"dependencies":{"react":{"version":">=16.9.0"},"prop-types":{"version":"15.8.1"},"antd":{"version":"4.24.3","css":"antd/dist/antd.css"},"react-dom":{"version":">=16.9.0"},"moment":{"version":"2.29.4"},"axios":{"version":"0.21.4"},"querystringify":{"version":"2.2.0"}},"identifier":"build-detail"},
  },
};
